#!/bin/sh
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname $(readlink $0))
FUNCTIONPATH=$SCRIPTPATH/func
FILETORUN=$FUNCTIONPATH/$1

if [ -z "$1" ] || [ "$1" == "--help" ]
then
	if [ -z "$1" ]
	then echo "Please specify the command to run"
	fi
	echo "Available command:"
	ls $FUNCTIONPATH
	exit 0
fi

if [ -f "$FILETORUN" ]; then
    $FILETORUN $2
else 
    echo "Command \"$1\" does not exist"
fi