#!/bin/sh

if [ "$1" == "--help" ]
then
  echo "usage: deploy [-v]"
fi

if [ "$1" == "-v" ]
then
  kubectl get deployment -o=jsonpath="{range .items[*]}{.metadata.name}{'|'}{range .spec.template.spec.containers[*]}{.image}{'\n'}{end}{end}" --all-namespaces | column -t -s "|" 
  exit 0
fi

echo "command "deploy $1" not found"